SET NAMES utf8;
INSERT INTO workshops (id, num, max, target, ampm, name) VALUES (1, 0, 36, 'kids',   'am', 'キッズワークショップ');
INSERT INTO workshops (id, num, max, target, ampm, name) VALUES (2, 0, 40, 'kids',   'am', 'キッズキッチン（ランチ編）');
INSERT INTO workshops (id, num, max, target, ampm, name) VALUES (3, 0, 30, 'adult',  'pm', 'ハッピー♪マインドマッピング');
INSERT INTO workshops (id, num, max, target, ampm, name) VALUES (4, 0, 50, 'adult',  'pm', 'ワールドカフェ');
INSERT INTO workshops (id, num, max, target, ampm, name) VALUES (5, 0, 40, 'adult',  'pm', '強み発見ワーク');
INSERT INTO workshops (id, num, max, target, ampm, name) VALUES (6, 0, 40, 'adult',  'pm', '「ママのイキイキ応援プログラム（通称ママイキ）」実践講座');
INSERT INTO workshops (id, num, max, target, ampm, name) VALUES (7, 0, 25, 'family', 'pm', '親子フラワーアレンジ');
INSERT INTO workshops (id, num, max, target, ampm, name) VALUES (8, 0, 30, 'family', 'pm', '親子お絵かきワークショップ');
INSERT INTO workshops (id, num, max, target, ampm, name) VALUES (9, 0, 20, 'family', 'pm', '親子キッチン（おやつ編）');
INSERT INTO workshops (id, num, max, target, ampm, name) VALUES (10, 0, 25,'family', 'pm', 'ファミリー・マッサージ');
INSERT INTO workshops (id, num, max, target, ampm, name) VALUES (11, 0, 10,'family', 'pm', 'ものがたりをつくろう');
