SET NAMES utf8;
INSERT INTO workshops (id, num, max, target, name) VALUES (1, 0, 36, 'kids',  'キッズワークショップ');
INSERT INTO workshops (id, num, max, target, name) VALUES (2, 0, 40, 'kids',  'キッズキッチン（ランチ編）');
INSERT INTO workshops (id, num, max, target, name) VALUES (3, 0, 30, 'adult', 'ハッピー♪マインドマッピング');
INSERT INTO workshops (id, num, max, target, name) VALUES (4, 0, 50, 'adult', 'ワールドカフェ');
INSERT INTO workshops (id, num, max, target, name) VALUES (5, 0, 40, 'adult', '強み発見ワーク');
INSERT INTO workshops (id, num, max, target, name) VALUES (6, 0, 40, 'adult', '「ママのイキイキ応援プログラム（通称ママイキ）」実践講座');
INSERT INTO workshops (id, num, max, target, name) VALUES (7, 0, 25, 'family','親子フラワーアレンジ');
INSERT INTO workshops (id, num, max, target, name) VALUES (8, 0, 30, 'family','親子お絵かきワークショップ');
INSERT INTO workshops (id, num, max, target, name) VALUES (9, 0, 20, 'family','親子キッチン（おやつ編）');
INSERT INTO workshops (id, num, max, target, name) VALUES (10, 0, 25,'family','ファミリー・マッサージ');
INSERT INTO workshops (id, num, max, target, name) VALUES (11, 0, 10,'family','ものがたりをつくろう');
